CREATE TABLE tb_role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority VARCHAR(20) NOT NULL
);

CREATE TABLE tb_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(60)  NOT NULL,
    email      VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    phone      VARCHAR(12)  NOT NULL,
    birth_date DATE         NOT NULL,
    role_id    BIGINT       NOT NULL,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES tb_role (id)
);

CREATE TABLE tb_user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES tb_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES tb_role (id)
);

CREATE TABLE tb_subject
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(40) NOT NULL,
    user_id BIGINT      NOT NULL,
    CONSTRAINT fk_subject_user FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

CREATE TABLE tb_study_session
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic                 VARCHAR(100) NOT NULL,
    duration_in_minutes   BIGINT       NOT NULL,
    break_time_in_minutes BIGINT,
    status                VARCHAR(20)  NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE,
    finished_date         TIMESTAMP WITHOUT TIME ZONE,
    user_id               BIGINT       NOT NULL,
    subject_id            BIGINT       NOT NULL,
    CONSTRAINT fk_study_session_user FOREIGN KEY (user_id) REFERENCES tb_user (id),
    CONSTRAINT fk_study_session_subject FOREIGN KEY (subject_id) REFERENCES tb_subject (id)
);

CREATE TABLE tb_revision
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date             DATE   NOT NULL,
    study_session_id BIGINT NOT NULL,
    CONSTRAINT fk_revision_study_session FOREIGN KEY (study_session_id) REFERENCES tb_study_session (id) ON DELETE CASCADE
);

CREATE TABLE tb_goal
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(40) NOT NULL,
    start_date   DATE        NOT NULL,
    end_date     DATE        NOT NULL,
    is_completed BOOLEAN     NOT NULL DEFAULT FALSE,
    user_id      BIGINT      NOT NULL,
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

CREATE TABLE tb_goal_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_in_minutes BIGINT  NOT NULL,
    is_completed      BOOLEAN NOT NULL DEFAULT FALSE,
    goal_id           BIGINT  NOT NULL,
    subject_id        BIGINT  NOT NULL,
    CONSTRAINT fk_goal_item_subject FOREIGN KEY (subject_id) REFERENCES tb_subject (id),
    CONSTRAINT fk_goal_item_goal FOREIGN KEY (goal_id) REFERENCES tb_goal (id)
);