CREATE TABLE tb_role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority VARCHAR(20) NOT NULL,

    CONSTRAINT uk_role_authority UNIQUE (authority)
);

CREATE TABLE tb_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(60)  NOT NULL,
    email      VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    phone      VARCHAR(12)  NOT NULL,
    birth_date DATE         NOT NULL
);

CREATE TABLE tb_user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
            REFERENCES tb_role (id)
);

CREATE TABLE tb_subject
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(40) NOT NULL,
    user_id BIGINT      NOT NULL,

    CONSTRAINT fk_subject_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id),

    CONSTRAINT uk_subject_user_name
        UNIQUE (user_id, name)
);

CREATE TABLE tb_topic
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    user_id BIGINT       NOT NULL,

    CONSTRAINT fk_topic_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id),

    CONSTRAINT uk_topic_user_name
        UNIQUE (user_id, name)
);

CREATE TABLE tb_study_session
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id              BIGINT NOT NULL,
    duration_in_minutes   BIGINT NOT NULL,
    break_time_in_minutes BIGINT NOT NULL,
    date                  DATE   NOT NULL,
    user_id               BIGINT NOT NULL,
    subject_id            BIGINT NOT NULL,

    CONSTRAINT fk_study_session_topic
        FOREIGN KEY (topic_id)
            REFERENCES tb_topic (id),

    CONSTRAINT fk_study_session_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id),

    CONSTRAINT fk_study_session_subject
        FOREIGN KEY (subject_id)
            REFERENCES tb_subject (id)
);

CREATE TABLE tb_revision
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_in_minutes   BIGINT,
    break_time_in_minutes BIGINT,
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    scheduled_date        DATE        NOT NULL,
    completed_date        DATE,
    session_id            BIGINT      NOT NULL,
    user_id               BIGINT      NOT NULL,

    CONSTRAINT fk_revision_study_session
        FOREIGN KEY (session_id)
            REFERENCES tb_study_session (id),

    CONSTRAINT fk_revision_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id)
);