CREATE TABLE tb_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL,
    name        VARCHAR(60)  NOT NULL,
    email       VARCHAR(100) NOT NULL UNIQUE,
    phone       VARCHAR(12),
    birth_date  DATE,

    CONSTRAINT uk_user_external_id UNIQUE (external_id)
);

CREATE TABLE tb_subject
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(40) NOT NULL,
    user_id BIGINT      NOT NULL,

    CONSTRAINT fk_subject_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id),

    CONSTRAINT uk_subject_user_name
        UNIQUE (user_id, name)
);

CREATE TABLE tb_topic
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    user_id BIGINT       NOT NULL,

    CONSTRAINT fk_topic_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id),

    CONSTRAINT uk_topic_user_name
        UNIQUE (user_id, name)
);

CREATE TABLE tb_study_session
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id              BIGINT NOT NULL,
    duration_in_minutes   BIGINT NOT NULL,
    break_time_in_minutes BIGINT NOT NULL,
    date                  DATE   NOT NULL,
    user_id               BIGINT NOT NULL,
    subject_id            BIGINT NOT NULL,

    CONSTRAINT fk_study_session_topic
        FOREIGN KEY (topic_id)
            REFERENCES tb_topic (id),

    CONSTRAINT fk_study_session_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id),

    CONSTRAINT fk_study_session_subject
        FOREIGN KEY (subject_id)
            REFERENCES tb_subject (id)
);

CREATE TABLE tb_revision
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_in_minutes   BIGINT,
    break_time_in_minutes BIGINT,
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    scheduled_date        DATE        NOT NULL,
    completed_date        DATE,
    session_id            BIGINT      NOT NULL,
    user_id               BIGINT      NOT NULL,

    CONSTRAINT fk_revision_study_session
        FOREIGN KEY (session_id)
            REFERENCES tb_study_session (id),

    CONSTRAINT fk_revision_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id)
);
